-- Run this in your Supabase SQL editor to create all tables

-- Participants: one row per session
create table participants (
    id              text primary key,           -- uuid generated by the app
    group_name      text not null,              -- "socratic" or "expository"
    age             text,
    education       text,
    prior_knowledge text,
    prob_familiarity text,
    consent_at      timestamptz default now(),
    completed       boolean default false
);

-- Session turns: one row per student message
create table session_turns (
    id              bigint generated always as identity primary key,
    participant_id  text references participants(id),
    turn_number     int not null,
    student_message text not null,
    tutor_reply     text not null,
    category        text,                       -- Paul & Elder category
    rationale       text,
    misconception_flag  boolean default false,
    misconception_label text,
    rubric_level    int,                        -- N0..N4 rubric score
    rubric_label    text,                       -- n0..n4 rubric label
    rubric_rationale text,                      -- short explanation for rubric assignment
    created_at      timestamptz default now()
);

-- Session analysis: one row per completed session
create table session_analysis (
    id                    bigint generated always as identity primary key,
    participant_id        text references participants(id),
    pattern               text,                 -- progression/resistance/loop/stagnation/breakthrough
    rationale             text,
    turning_point         text,
    dominant_category     text,
    misconception_resolved boolean,
    created_at            timestamptz default now()
);

-- Evaluation: one row per submitted questionnaire
create table evaluation (
    id                  bigint generated always as identity primary key,
    participant_id      text references participants(id),
    q1_understanding    int,
    q2_autonomy         int,
    q3_engagement       int,
    q4_frustration      int,
    q5_adaptation       int,
    q6_open             text,
    created_at          timestamptz default now()
);
